<template>
  <div>
    <Nav v-on:goMenu="onGoMenu" />

    <!-- Header -->
    <header class="masthead bg-primary text-white text-center">
      <div class="container">
        <img class="img-fluid mb-5 d-block mx-auto" src="img/profile.png" alt="">
        <h1 class="text-uppercase mb-0">Start Everikey</h1>
        <hr class="star-light">
        <h2 class="font-weight-light mb-0">Everikey is absolutely most creative one in the world!</h2>
      </div>
    </header>

    <!-- generate Section -->
    <section id="generate">
      <div class="container">
        <h2 class="text-center text-uppercase text-secondary mb-0">Generate Everikey</h2>
        <hr class="star-dark mb-5">        
        <Geverikey />
      </div>
    </section>

    <!-- Portfolio Grid Section -->
    <section class="portfolio" id="portfolio">
      <div class="container">
        <h2 class="text-center text-uppercase text-secondary mb-0">Marketplace</h2>
        <hr class="star-dark mb-5">
        <Portfolio />
      </div>
    </section>

    <!-- About Section -->
    <section class="bg-primary text-white mb-0" id="about">
      <div class="container">
        <h2 class="text-center text-uppercase text-white">About</h2>
        <hr class="star-light mb-5">
        <div class="row">
          <div class="col-lg-4 ml-auto">
            <p class="lead">Generating Identicon with NFT(Non Fungible Token). Each identicon can be generated by user’s painting within a square grid system and non-fungible. It connect with user’s address and unique account name.</p>
          </div>
          <div class="col-lg-4 mr-auto">
            <p class="lead">Everikey is a unique shaped avatar that is generated using a user's own public key. Your everikey is unique, no one has the same everikey as you.</p>
          </div>
        </div>
        <div class="text-center mt-4">
          <a class="btn btn-xl btn-outline-light" href="#">
            <i class="fas fa-download mr-2"></i>
            Try it!
          </a>
        </div>
      </div>
    </section>

    <!-- Contact Section -->
    <section id="contact">
      <div class="container">
        <h2 class="text-center text-uppercase text-secondary mb-0">Contact Us</h2>
        <hr class="star-dark mb-5">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
            <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
            <form name="sentMessage" id="contactForm" novalidate="novalidate">
              
              <div class="control-group">
                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                  <label>Email Address</label>
                  <input class="form-control" id="email" type="email" placeholder="Email Address" required="required" data-validation-required-message="Please enter your email address.">
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              
              <br>
              <div id="success"></div>
              <div class="form-group">
                <button type="submit" class="btn btn-primary btn-xl" id="sendMessageButton">Send</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    

    <div class="copyright py-4 text-center text-white">
      <div class="container">
        <small>Copyright &copy; Website 2018</small>
      </div>
    </div>


  </div>
</template>

<script>
import Nav from '~/components/landing/Nav.vue'
import Geverikey from '~/components/landing/Geverikey.vue'
import Portfolio from '~/components/landing/Portfolio.vue'

export default {
  components: {
    Nav,
    Geverikey,
    Portfolio
  },

  mounted() {    
    
  },

  methods: {
    onGoMenu(hash) {      
      if(hash){
        this.$scrollTo(`#${hash}`, 500, {offset: -60})                
      }
    }
  }  
}
</script>
<style scoped>

section {
  padding: 6rem 0;
}

section h2 {
  font-size: 2.25rem;
  line-height: 2rem;
}

@media (min-width: 992px) {
  section h2 {
    font-size: 3rem;
    line-height: 2.5rem;
  }
}


header.masthead {
  padding-top: calc(6rem + 72px);
  padding-bottom: 6rem;
}

header.masthead h1 {
  font-size: 3rem;
  line-height: 3rem;
}

header.masthead h2 {
  font-size: 1.3rem;
  font-family: 'Lato';
}

@media (min-width: 992px) {
  header.masthead {
    padding-top: calc(6rem + 106px);
    padding-bottom: 6rem;
  }
  header.masthead h1 {
    font-size: 4.75em;
    line-height: 4rem;
  }
  header.masthead h2 {
    font-size: 1.75em;
  }
}


.portfolio {
  margin-bottom: -15px;
}

@media (min-width: 576px) {
  .portfolio {
    margin-bottom: -30px;
  }  
}


.footer {
  padding-top: 5rem;
  padding-bottom: 5rem;
  background-color: #2C3E50;
  color: #fff;
}

.copyright {
  background-color: #1a252f;
}


</style>